### ISSUE TITLE
Chapter 4 - kubia-liveness-probe.yaml (Book issue) 

### ISSUE THREAD

**Issue by iSimar** [luksa/kubernetes-in-action#3]
https://github.com/luksa/kubernetes-in-action/blob/master/Chapter04/kubia-liveness-probe.yaml

In the book the content of file `kubia-liveness-probe.yaml` has 
```
Kind: pod
```

Fix: `pod` -> `Pod`

Got this error
```
error: unable to recognize "kubia-liveness-probe.yaml": no matches for kind "pod" in version "v1"
```

**Comment by luksa** [comment]
Yes, this error is already listed in the book's errata page: https://manning-content.s3.amazonaws.com/download/b/882bfe0-82a4-47f7-bf02-610f3b25c600/Luksa_KubernetesinAction_Err3.html

But thank you for reporting.
